engines:
  pylint:
    enabled: true      # Detects style violations, code smells, etc.
  flake8:
    enabled: true      # Lightweight style and formatting linter
  bandit:
    enabled: true      # Security scanner for Python
  radon:
    enabled: true      # Analyzes code complexity (Cyclomatic Complexity, LOC, etc.)
  mypy:
    enabled: true      # Static type checker for Python
  duplication:
    enabled: true
    minimumTokens: 5
    threshold: 10

tools:
  pylint:
    configuration:
      config: .pylintrc

  flake8:
    configuration:
      config: .flake8
